name: Azure Login

on: [push]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Show Azure Subscription ID
        run: |
          az account show --output table
