name: Azure CLI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/setup-azure-cli@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: List resource groups
      run: |
        az group list --output table
